FROM harisekhon/jython:2.7
ADD hgsc_vcf /opt/hgsc_vcf
ADD annotate_vcf_cosmic.py /opt/annotate_vcf_cosmic.py

# export JYTHONPATH=/hgsc_software/cancer-analysis/halotron/illumina/illumina_v0.0.2/halotron/site-packages
# export CLASSPATH=/hgsc_software/cancer-analysis/code/javalib/sqlite-jdbc-3.8.11.2/sqlite-jdbc-3.8.11.2.jar:/hgsc_software/cancer-analysis/code/picard-tools-1.129/picard.jar:/hgsc_software/cancer-analysis/code/picard-tools-1.129/picard-lib.jar:/hgsc_software/cancer-analysis/code/picard-tools-1.129/htsjdk-1.129.jar:/hgsc_software/cancer-analysis/code/krcgtk/krcgtk-0.01.jar:$CLASSPATH
